# Generated by Django 4.1.7 on 2023-02-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('size', models.CharField(max_length=150)),
                ('url', models.CharField(max_length=250, null=True)),
                ('data', models.TextField(default='')),
                ('filename', models.CharField(default='', max_length=150)),
                ('type', models.CharField(default='', max_length=150)),
                ('created_at', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gallery',
                'verbose_name_plural': 'Gallery',
            },
        ),
    ]
