# Generated by Django 4.1.7 on 2023-02-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bucket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='files',
            field=models.FileField(null=True, upload_to='fb'),
        ),
    ]
