# Generated by Django 4.1.7 on 2023-02-27 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bucket', '0003_gallery_code_alter_gallery_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='files',
        ),
    ]
